version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    working_directory: ~/angular-circle-demo
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: angular-circle-demo-{{ .Branch }}-{{ checksum "package-lock.json"}}
      - run: npm install
      - save_cache:
          key: angular-circle-demo-{{ .Branch }}-{{ checksum "package-lock.json"}}
          paths:
            - "nodes_modules"
      - run: npm run build
      - deploy:
          command: |
            ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
workflows:
    build-and-test:
      jobs:
        - build-and-test
